name: pdf_convertor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  shared_preferences: ^2.3.2 
  file_picker: ^10.3.2
  syncfusion_flutter_pdf: ^30.2.6
  path_provider: ^2.1.5
  salomon_bottom_bar: ^3.3.2
  pdf: ^3.10.4
  open_filex: ^4.5.0 
  image_picker: ^1.1.2
  reorderables: ^0.6.0
  share_plus: ^11.1.0
  path: ^1.8.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
